# vbase bridge configurations
# general
[general]
    port=8088
    # log level
    # debug
    # fatal
    # error
    # warning
    # info
    log_level="info"

# loraser configurations
# [loraserver]
#     server="http://113.108.88.121:8900/api"
#     username="admin"
#     password="admin"

# lora backend configurations
[lora_backend]
    # sport http/mqtt backend
    # http port
    http_port=8880
    [lora_backend.mqtt]
        server="tcp://broker.hivemq.com:1883"
        username=""
        password=""
        qos=0
        clean_session=true
        client_id="maxiiot-device-lora" 
        ca_cert=""
        tls_cert="" 
        tls_key=""
        uplink_topic_template="application/+/device/%s/rx"
        #   ack_topic_template="application/+/device/+/ack"

# postgres dsn (e.g.: postgres://user:password@hostname/database?sslmode=disable).
[postgres]
    auto_migrate=true 
    dsn="postgres://devicebridge:devicebridge@192.168.181.85:25432/devicebridge?sslmode=disable"

[publisher]
   [publisher.mqtt]
        server="tcp://broker.hivemq.com:1883"
        username=""
        password=""
        qos=0
        clean_session=true
        client_id="maxiiot-device-bridge" 
        ca_cert=""
        tls_cert="" 
        tls_key=""