version: "3"

networks:
  lora_default:
    external: true

services:
  devicebridge:
    image: maxiiot/devicebridge:v0.1.0
    ports:
      - 8088:8088
    depends_on:
      - postgres 
    restart: always
    volumes:
      - ./config/devicebridge/app.toml:/usr/local/devicebridge/app.toml
    networks:
      - lora_default
  
  postgres_devicebridge:
    image: postgres:9.6-alpine
    ports:
      - 5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=devicebridge
      - POSTGRES_USER=devicebridge
      - POSTGRES_DB=devicebridge
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - lora_default
